name: Apply to B12

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get run URL
        id: vars
        run: echo "RUN_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests

      - name: Run script
        run: |
          sed -i "s|TO_BE_FILLED|$RUN_URL|g" submit.py
          python main.py